# Generated by Django 3.1 on 2020-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_auto_20200817_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sotrie',
            new_name='Sortie',
        ),
    ]
