# Generated by Django 3.1 on 2020-08-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20200817_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='qte_stoke',
            new_name='qte_stocke',
        ),
    ]
