# Generated by Django 3.1 on 2020-08-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_auto_20200817_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='option',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
